version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27016:27017"
    volumes:
      - mongodb_data:/data/db

  backend22:
    build: .
    container_name: backend_app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      DATABSE_URL: "mongodb://mongodb:27017"

volumes:
  mongodb_data:
